# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iFOixhXucsisV95LIGeE7laipQ4J0rcf
"""

#object oriented programming
#example 1

class triangle(object):
  number_of_sides=3
  def _init_(self,angle1,angle2,angle3):
    self.angle1=angle1
    self.angle2=angle2
    self.angle3=angle3
def check_angles(self):
  if self.angle1+self.angle2+self.angle3==180:
    return true
   else:
     return false

my_triangle=triangle(30,60,90)
print my_triangle.number_of_sides
print my_triangle.check_angle()

#examlpe 2

class employee:
  def _init_(self,name):
    self.name = name
  def display(self):
    print('the name of employee is:',self.name)
 frist = employee('rushabh')
 second = emlpoyee('dhaval')
 second.display()
 frist.display()
